### ISSUE TITLE
Implement CircleCI API v2

### ISSUE THREAD

**Issue by orion434** [EvolEcolGroup/EEG_Docker#3]
- [x] Find where new API is needed 
=> `.circleci/config.yml` (`call_test_image_job` and `check_update_docker`)
- [x] Implement new API
=> Implemented but still producing errors
- [x] Test until works with no error
- [x] Merge with master
- [x] Rebase mtDnaCombine - All test passed
- [x] Deleted mtDNAcombine_backup

**Comment by orion434** [comment]
Reference docs:

- [CircleCI API v2 - Resources/Docs website](https://circleci.com/docs/api/v2/?mkt_tok=eyJpIjoiWlRkbE1URmxPVFJoWkdNNSIsInQiOiJKUHJCM2ZWVGFmNkNDWXFVYm9Pa1lYWTZvSENteUNJaEZwYUNlUnRrZUxNVmh5ZWFacUlRUnhrZ3JMUE5ycVFsM3IyZnR5UFgwZmRTU3c1bDlJamdDdmNsWTR4NlF5NUtJUmdLem1WVnN5M3FrNlZrdm5CT0NKMmtxSUQwSzlaeCJ9#circleci-api)

- [API Reference (v1.1 and v.2)](https://circleci.com/docs/2.0/api-intro/?mkt_tok=eyJpIjoiWlRkbE1URmxPVFJoWkdNNSIsInQiOiJKUHJCM2ZWVGFmNkNDWXFVYm9Pa1lYWTZvSENteUNJaEZwYUNlUnRrZUxNVmh5ZWFacUlRUnhrZ3JMUE5ycVFsM3IyZnR5UFgwZmRTU3c1bDlJamdDdmNsWTR4NlF5NUtJUmdLem1WVnN5M3FrNlZrdm5CT0NKMmtxSUQwSzlaeCJ9)

**Comment by orion434** [comment]
**Reference to API v2 in** 

- `refernces:` => **call_test_image_job**`: &call_test_image_job` 
(Code for calling the test of the image via the curl request)
  which is called from 
  - `jobs` \ `build_deploy_docker` \ `steps` \ **call_test_image_job**

    `build_deploy_docker` called from 
    - API v2 inside **check_update_docker**, see next 1st-level bullet point (to avoid duplicate)
    - `workflows` \ `manual_build_deploy_docker` \ `jobs` \ `build_deploy_docker ` 

  - `jobs` \ `test_curl_trigger` \ `steps` \ **call_test_image_job**
    - `workflows` \ `manual_test_image` \ `jobs` \ `test_curl_trigger`

- **check_update_docker**
  which is called from:
  - `workflows` \ `update_docker` \ **check_update_docker**
  - `workflows` \ `cron_workflow` \ **check_update_docker**

Affected Jobs:
```
jobs:
  build_deploy_docker:
    [...]
    steps:
      - checkout
      - *build_docker
      - *call_test_image_job
  [...]
  test_curl_trigger:  
    [...]
    steps:
      - *call_test_image_job   
```

Affected Workflows:
```
workflows:
  version: 2
  manual_test_image:
    jobs:
      - wait_manual_approval:
           type: approval 
      - test_curl_trigger:     
           requires:
           - wait_manual_approval
  manual_build_deploy_docker:
    jobs:
      -  wait_manual_approval:
          type: approval
      - build_deploy_docker:
          requires:
          - wait_manual_approval
  update_docker:
     jobs:
       - check_update_docker 
   cron_workflow:  
      triggers: [...]
      jobs:
        - check_update_docker 
```

**Comment by orion434** [comment]
Actions
Test that following workflow run with no error:
- [ ] `workflows` \ `manual_test_image` => `test_curl_trigger` \ **call_test_image_job**

- [ ] `workflows` \ `manual_build_deploy_docker` => `build_deploy_docker` \ **call_test_image_job**
- [ ] `workflows` \ `update_docker` => **check_update_docker**
  [Circle CI - #213](https://circleci.com/gh/EvolEcolGroup/EEG_Docker/213) Passing the test but curl request reply is "Not found"

No need to test:
-  `workflows` \ `cron_workflow` => **check_update_docker**

**Comment by orion434** [comment]
Added `DOCKER_TOKEN_GLS:` a Circleci personal API token - A personal one (instead of a project one) is now needed to trigger workflows with API v2. (The value is added in the project environment variables)

```
# Pipeline parameter to run conditional workflows - 21 April 2020
parameters:
  run_on_commit:
    type: boolean
    default: true
  run_after_check_update:
    type: boolean
    default: false

```
